- name: gather facts about servers
  hosts:  web_servers
  vars:
    ansible_user: ec2-user
  
  tasks:
    - name: Create user named test-user
      user:
        name: test-user
        state: present
      register: user_created_status
    
    - name: User creation status
      debug:
        msg: "User creation status for user test-user is: {{ 'Success' if user_created_status.failed == false else 'Failed' }}"