---

- hosts: all
  become: true
  tasks:
  - name: Install Apache and PHP packages to Amazon Linux EC2 and update cache
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes