---

- hosts: all
  become: true
  tasks:
  - name: Install Apache and PHP packages to Amazon Linux EC2 and update cache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes