- name: gather facts about servers
  hosts:  web_servers
  vars:
    ansible_user: ec2-user
  
  tasks:
    - name: Install latest httpd
      yum:
        name: httpd
        state: latest

    - name: Start httpd
      ansible.builtin.service:
        name: httpd
        state: started

    
    - name: Create default index page
      template: 
        src: index.html.j2
        dest: /var/www/html/index.html